/* eslint-disable quote-props */
/* eslint comma-dangle: ["error", "always"] */
export default {
  'test': {
    'basic': 'english',
    'interpolation': 'quoine-{{name}}',
  },
  'trade-overview': {
    'baseOpenPrice': 'Base Price',
    'pnl': 'P&L',
    'position': 'Pos.',
  },
  'history': {
    'all-orders': 'All Orders',
    'executions': 'Executions',
    'live-orders': 'Live Orders',
    'positions': 'Positions',
  },
  'book': {
    'group': 'group orders',
    'feed': 'trade feed',
  },
  'order': {
    'avg-price': 'Avg. Price',
    'buy': 'Buy',
    'buys': 'Buys',
    'cancel': 'Cancel',
    'cancelled': 'Cancelled',
    'close': 'Close',
    'created-at': 'Created at',
    'disclose-quantity': 'Disclose Qty.',
    'distance': 'Price Distance',
    'distance-type': 'Distance Type',
    'edit-price': 'Edit price',
    'edit-quantity': 'Edit qty.',
    'est-price': 'Est. Cost',
    'fiat': 'Fiat',
    'percentage': 'Percent',
    'fee': 'Fee',
    'filled': 'Filled',
    'filled-qty': 'Filled Qty.',
    'id': 'ID',
    'interest': 'Daily Interest',
    'leverage': 'Leverage',
    'limit': 'Limit',
    'live': 'Live',
    'margin': 'Margin',
    'market': 'Market',
    'market_with_range': 'Range',
    'mode': 'Mode',
    'net-out': 'Net-Out',
    'new': 'New',
    'one-direction': 'One Direction',
    'open-price': 'Open Price',
    'price': 'Price',
    'product': 'Product',
    'quantity': 'Quantity',
    'sell': 'Sell',
    'sells': 'Sells',
    'side': 'Side',
    'slippage': 'Slippage',
    'spot': 'Spot',
    'status': 'Status',
    'stop': 'Stop',
    'target': 'Target',
    'two-direction': 'Two Direction',
    'type': 'Type',
  },
  'order-modal': {
    'create-confirm': 'Order Confirmation',
    'create-finish-submitted': 'Order Submitted',
    'create-finish-filled': 'Order Filled',
    'cancel-confirm': 'Order Cancel Confirmation',
    'cancel-finish': 'Order Cancelled',
    'edit-confirm': 'Order Update Confirmation',
    'edit-finish': 'Order Updated',
  },
  'position': {
    'account': 'Account',
    'all': 'All',
    'close': 'close',
    'close-pnl': 'Closed P&L',
    'close-price': 'Close Price',
    'close-qty': 'Closed Qty.',
    'created-at': 'Created at',
    'edit-stopLoss': 'Edit SL',
    'edit-takeProfit': 'Edit TP',
    'id': 'ID',
    'long': 'Long',
    'longs': 'Longs',
    'margin': 'Margin',
    'open-pnl': 'Open P&L',
    'open-price': 'Open Price',
    'open-qty': 'Open Qty.',
    'pnl': 'Est. P&L',
    'position': 'Position',
    'product': 'Product',
    'quantity': 'Quantity',
    'short': 'Short',
    'shorts': 'Shorts',
    'side': 'Side',
    'stop-loss': 'Stop Loss',
    'take-profit': 'Take Profit',
    'to-close-qty': 'Qty. To Close',
    'total-interest': 'Total Int.',
  },
  'position-modal': {
    'close-confirm': 'Position Close Confirmation',
    'close-finish': 'Position Closed',
    'edit-confirm': 'Position Update Confirmation',
    'edit-finish': 'Position Updated',
  },
  'execution': {
    'created-at': 'Created at',
    'id': 'ID',
    'order-id': 'Order ID',
    'price': 'Price',
    'product': 'Product',
    'quantity': 'Quantity',
    'side': 'Side',
    'target': 'Target',
  },
  'menu': {
    'accounts': 'Accounts',
    'dashboard': 'Dashboard',
    'setting': 'Setting',
  },
  'product': {
    'high': 'High',
    'low': 'Low',
    'volume': '24h Volume',
  },
  'account': {
    'balance': 'Balance',
    'balance-base': 'Crypto Balance',
    'balance-quote': 'Fiat Balance',
    'balance-total': 'Total Balance',
    'equity': 'Equity',
    'margin-available': 'Margin Available',
    'margin-coverage': 'Margin Coverage',
    'margin-used': 'Margin Used',
    'pnl': 'P&L',
  },
  'common': {
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'dismiss': 'Dismiss',
    'load-more': 'Load',
    'margin': 'Margin',
    'spot': 'Spot',
    'submit': 'Submit',
  },
  'confirmation': {
    'skip': 'Skip this confirmation in the future. (You can change this in Setting page)',
  },
  'sign-in': {
    'action': 'Sign in',
    'code': 'Code',
    'email': 'Email',
    'need-code': '2-Factor Authentication is enabled for your account. Please enter your authentication code below. You can get it from Authy app or via SMS.',
    'password': 'Password',
    'resend-sms': 'Resend code via SMS',
    'title': 'Sign in',
    'use-all-features': 'Sign in to use all features of QUOINE Exchange',
  },
  'error': {
    'order-direction-long-need-empty': 'You must have no long trades to place sell order',
    'order-direction-short-need-empty': 'You must have no short trade to place buy order',
    'order-price-bigger-than-min': 'Order price must bigger than 1',
    'order-price-limit-bigger-than-market-bid': 'Order sell limit price must bigger than market bid',
    'order-price-limit-smaller-than-market-ask': 'Order buy limit price must smaller than market ask',
    'order-price-stop-bigger-than-market-ask': 'Order buy stop price must bigger than market ask',
    'order-price-stop-smaller-than-market-bid': 'Order sell stop price must smaller than market bid',
    'order-quantity-bigger-than-min': 'Order quantity must bigger than 0.01',
    'order-quantity-smaller-than-max': 'Order quantity must smaller than 100',
    'other': 'Internal error',
  },
};
