/* eslint-disable */

export default {
  "test": {
    "basic": "english",
    "interpolation": "quoine-{{name}}"
  },
  "whats-new": {
    "date": "1471345199",
    "title": "What's new",
    "heading": "This can be found in side menu",
    "button": "We have updated!"
  },
  "trade-overview": {
    "baseOpenPrice": "Base Price",
    "pnl": "P&L",
    "position": "Pos."
  },
  "history": {
    "all-orders": "All Orders",
    "executions": "Executions",
    "live-orders": "Live Orders",
    "positions": "Positions"
  },
  "book": {
    "group": "group orders",
    "feed": "trade feed"
  },
  "chart": {
    "add-sub-chart": "Add sub chart",
    "remove-sub-chart": "Remove sub chart"
  },
  "blotter": {
    "switch-layout": "Switch Layout"
  },
  "order": {
    "all": "All",
    "avg-price": "Avg. Price",
    "buy": "Buy",
    "buys": "Buys",
    "cancel": "Cancel",
    "cancelled": "Cancelled",
    "close": "Close",
    "created-at": "Created at",
    "disclose-quantity": "Disclose Qty.",
    "distance": "Price Distance",
    "distance-type": "Distance Type",
    "edit-price": "Edit price",
    "edit-quantity": "Edit qty.",
    "est-price": "Est. Cost",
    "fiat": "Fiat",
    "percentage": "Percent",
    "fee": "Fee",
    "filled": "Filled",
    "filled-qty": "Filled Qty.",
    "id": "ID",
    "interest": "Daily Interest",
    "leverage": "Leverage",
    "limit": "Limit",
    "live": "Live",
    "margin": "Margin",
    "market": "Market",
    "market_with_range": "Range",
    "mode": "Mode",
    "net-out": "Net-Out",
    "new": "New",
    "one-direction": "One Direction",
    "open-price": "Open Price",
    "price": "Price",
    "product": "Product",
    "quantity": "Quantity",
    "sell": "Sell",
    "sells": "Sells",
    "side": "Side",
    "slippage": "Slippage",
    "spot": "Spot",
    "status": "Status",
    "stop": "Stop",
    "target": "Target",
    "two-direction": "Two Direction",
    "type": "Type",
    "trailing_stop": "Trailing St.",
    "no-order-title": "there is no order"
  },
  "order-modal": {
    "create-confirm": "Order Confirmation",
    "create-finish-submitted": "Order Submitted",
    "create-finish-filled": "Order Filled",
    "cancel-confirm": "Order Cancel Confirmation",
    "cancel-finish": "Order Cancelled",
    "edit-confirm": "Order Update Confirmation",
    "edit-finish": "Order Updated"
  },
  "position": {
    "account": "Account",
    "all": "All",
    "close": "close",
    "closed": "Closed",
    "open": "Open",
    "status": "Status",
    "close-all": "Close All",
    "close-long": "Close Longs",
    "close-short": "Close Shorts",
    "close-pnl": "Closed P&L",
    "close-price": "Close Price",
    "close-qty": "Closed Qty.",
    "created-at": "Created at",
    "edit-stopLoss": "Edit SL",
    "edit-takeProfit": "Edit TP",
    "id": "ID",
    "long": "Long",
    "longs": "Longs",
    "margin": "Margin",
    "open-pnl": "Open P&L",
    "open-price": "Open Price",
    "open-qty": "Open Qty.",
    "pnl": "Est. P&L",
    "position": "Position",
    "product": "Product",
    "quantity": "Quantity",
    "short": "Short",
    "shorts": "Shorts",
    "side": "Side",
    "stop-loss": "Stop Loss",
    "take-profit": "Take Profit",
    "to-close-qty": "Qty. To Close",
    "total-interest": "Total Int.",
    "no-position-title": "there is no position"
  },
  "position-modal": {
    "close-confirm": "Position Close Confirmation",
    "close-finish": "Position Closed",
    "edit-confirm": "Position Update Confirmation",
    "edit-finish": "Position Updated"
  },
  "execution": {
    "created-at": "Created at",
    "id": "ID",
    "order-id": "Order ID",
    "price": "Price",
    "product": "Product",
    "quantity": "Quantity",
    "side": "Side",
    "target": "Target",
    "takerSide": "Side",
    "all": "All",
    "buy": "Buy",
    "sell": "Sell"
  },
  "menu": {
    "accounts": "Accounts",
    "dashboard": "Dashboard",
    "settings": "Settings",
    "language": "Language",
    "classic": "Back to Classic",
    "whats-new": "What's New"
  },
  "product": {
    "high": "High",
    "low": "Low",
    "volume": "24h Volume",
    "add": "Add Product"
  },
  "account": {
    "add": "Add Account",
    "balance": "Balance",
    "balance-available": "Available Balance",
    "balance-base": "Crypto Balance",
    "balance-locked": "Locked Balance",
    "balance-quote": "Fiat Balance",
    "balance-total": "Total Balance",
    "balance-total-fiat": "Total Fiat Balance",
    "balance-total-crypto": "Total Crypto Balance",
    "equity": "Equity",
    "interest-earned": "Interest Earned",
    "limit-orders": "Limit Orders",
    "loan-offers": "Loan Offers",
    "loaned-out": "Loaned Out",
    "margin-available": "Available Margin",
    "margin-coverage": "Margin Coverage",
    "margin-used": "Used Margin",
    "pnl": "P&L"
  },
  "common": {
    "cancel": "Cancel",
    "confirm": "Confirm",
    "dismiss": "Dismiss",
    "load-more": "Load",
    "margin": "Margin",
    "spot": "Spot",
    "submit": "Submit",
    "view": "View",
    "edit": "Edit",
    "delete": "Delete",
    "update": "Update",
    "add": "Add",
    "choose-file": "Choose File",
    "change-file": "Change File"
  },
  "confirmation": {
    "skip": "Skip this confirmation in the future. (You can change this in Setting page)"
  },
  "sign-in": {
    "action": "Sign in",
    "code": "Code",
    "email": "Email",
    "need-code": "2-Factor Authentication is enabled for your account. Please enter your authentication code below. You can get it from Authy app or via SMS.",
    "password": "Password",
    "resend-sms": "Resend code via SMS",
    "title": "Sign in",
    "use-all-features": "Sign in to use all features of QUOINE Exchange",
    "sign-up": "Sign up",
    "forgot-password": "Forgot password"
  },
  "forgot-password": {
    "title": "Forgot password",
    "heading": "Reset your password",
    "email": "Email",
    "check-email": "We've just sent you an email with a reset link. Please check your password. Didn't receive any mail? Check your spam or",
    "resent-successfully": "Password reset email resent successfully.",
    "send": "Send Reset Password Email",
    "resend": "Resend Resend Password Email"
  },
  "reset-password": {
    "title": "Reset password",
    "heading": "Enter new password",
    "password": "Password",
    "success-title": "Reset password successfully",
    "success-action": "Go to sign in",
    "success-message": "Reset password successfully"
  },
  "sign-up": {
    "action": "Sign up",
    "title": "Sign up",
    "country": "Country of Residence",
    "nationality": "Nationality",
    "first-name": "First name",
    "last-name": "Last name",
    "email": "Email",
    "password": "Password",
    "affiliate-code": "Promotion code (Optional)",
    "term-condition": "I agree with terms & conditions",
    "success-title": "Sign up successfully",
    "success-action": "Go to sign in",
    "success-message": "Thank you for registering. Your registration is almost complete. An email has been sent with further instructions.",
    "sign-in": "Sign in",
    "error-unique-email": "Email is already taken.",
    "error-password": "Password need to be at least 8 characters. Password must contain at least one (1) upper case letter, one (1) lower case letter, and one (1) number.",
    "error-term-condition": "You need to accept terms and condition in order to proceed",
  },
  "sign-out": {
    "action": "Sign out",
    "title": "Do you want to sign out?",
    "from-all-devices": "Do you want to sign out from all devices and browsers?"
  },
  "error": {
    "order-direction-long-need-empty": "You must have no long trades to place sell order",
    "order-direction-short-need-empty": "You must have no short trade to place buy order",
    "order-price-bigger-than-min": "Order price must be larger than 1",
    "order-price-limit-bigger-than-market-bid": "Order sell limit price must be larger than market bid",
    "order-price-limit-smaller-than-market-ask": "Order buy limit price must be smaller than market ask",
    "order-price-stop-bigger-than-market-ask": "Order buy stop price must be larger than market ask",
    "order-price-stop-smaller-than-market-bid": "Order sell stop price must be smaller than market bid",
    "order-quantity-bigger-than-min": "Order quantity must be bigger than 0.01",
    "order-quantity-smaller-than-max": "Order quantity must be smaller than 100",
    "other": "Internal error",
    "position-stop-loss-smaller-than-market-bid": "Position stop loss must be smaller than market bid",
    "position-stop-loss-larger-than-market-ask": "Position stop loss must be larger than market ask",
    "position-take-profit-larger-than-market-bid": "Position take profit must be larger than market bid",
    "position-take-profit-smaller-than-market-ask": "Position take profit must be smaller than market ask",
    "token-is-invalid": "Token is invalid",
    "your-password-is-incorrect": "Your password is incorrect",
    "password-update-failed": "Password update failed",
    "internet-connection": "Internet connection error",
    "fund-date-can't-be-blank": "Fund date can't be blank",
    "verification-failed": "Verification failed",
    "bank-statement-can't-be-blank": "Bank statement can't be blank",
  },
  "language": {
    "en": "English",
    "ja": "日本語"
  },
  "transaction": {
    "title-all": "All Transactions",
    "id": "Id",
    "created-at": "Created At",
    "loan_fee": "Interest Payment Fee",
    "trade_fee": "Exchange Fee",
    "debit": "Debit",
    "credit": "Credit",
    "loan": "Loan",
    "repay": "Repay",
    "loan_trade": "Repay",
    "interest_transfer": "Interest Transfer",
    "fund": "Fund",
    "bought": "Bought",
    "sold": "Sold",
    "cross_ccy_trade": "Cross CCY Trade",
    "withdraw": "Withdraw",
    "hot_wallet_settlement": "Withdraw",
    "system_transfer": "System Transfer",
    "credit_new_register": "New Client Credit",
    "credit_referrer": "Referral Credit",
    "direct_trade": "Trade"
  },
  "volume": {
    "title": "Transacted Volumes",
    "email-report": "Email Report",
    "email-report-choose-range-first": "You need to choose \"From\" and \"To\" date for the email report.",
    "from": "From",
    "to": "To"
  },
  "volume-modal": {
    "report-sent": "Report sent",
    "report-check-email": "Please check your email inbox for the report"
  },
  "fund": {
    "title": "Fund",
    "fiat-instruction": "To fund your QUOINE {{- currency}} account, please wire the funds to the account below. Note that your Account Name must match your registered name.",
    "crypto-instruction": "To fund your QUOINE {{- currency}} account, please send the funds to the address below.",
    "not-support-funding": "Were are not support funding QUOINE {{- currency}} account at the moment. Please contact us if you have any question.",
    "fund-another": "To fund another account, please select it from the top menu."
  },
  "withdrawal": {
    "title": "Withdrawal",
    "action": "Submit Withdraw",
    "fiat-instruction": "To withdraw from your QUOINE {{- currency}} account, please choose a bank account and enter the withdrawal amount below.",
    "crypto-instruction": "To withdraw from your QUOINE {{- currency}} account, please enter your {{- currency}} address and the withdrawal amount below.",
    "withdraw-another": "To withdraw from another account, please select it from the top menu.",
    "bank-account": "Bank Account",
    "token": "Token",
    "amount": "Amount",
    "request": "Request",
    "pending": "Pending",
    "pending-title": "Pending withdrawals",
    "no-pending-title": "No Pending withdrawals",
    "success-message": "Withdrawal successfully",
    "cancel-confirm-title": "Cancel Withdrawal Confirmation",
    "cancel-confirm-message": "Are you sure you want to cancel this withdrawal?",
    "cancel-finish-message": "Cancel Withdrawal successfully",
    "request-token-title": "Request authentication token",
    "request-token-message": "Authentication code has been sent to your email address",
  },
  "asset-transfer": {
    "pending-message": "We require ID and other documents before you can do a fiat deposit/withdrawal.<br/>Please upload your proof documents in <strong>Settings Page</strong>",
    "declined-message": "Your proof documents have been declined.<br/>Our staff has reviewed your proof documents. Unfortunately, we were unable to approve them.<br/>Please correct issues and upload your proof documents again in <strong>Settings Page</strong>",
    "goto-settings-page": "Go to Settings Page",
  },
  "bank": {
    "name": "Bank Name",
    "branch": "Branch",
    "bankAddress": "Address",
    "swift": "SWIFT",
    "swift-check": "SWIFT check",
    "bank-statement": "Bank statement",
    "reason": "Reason",
    "accName": "Account Name",
    "accType": "Account Type",
    "accNumber": "Account Number",
    "status": "Status",
    "pending": "Pending",
    "edit": "Edit",
    "new": "New Account",
    "delete-comfirm-title": "Confirmation",
    "delete-comfirm-message": "Do you want to delete this bank account?",
    "delete-success-message": "Delete bank account successfully.",
    "create-title": "Create new",
    "create-heading": "Create new bank account",
    "create-success-message": "Create new bank account successfully.",
    "update-title": "Update bank account",
    "update-heading": "Update bank account",
    "update-success-message": "Update bank account successfully."
  },
  "expedite": {
    "title": "Expedite",
    "action": "Create funding request",
    "description": "To EXPEDITE funding of your account, please enter the information below. Failure in submitting these details will result in delays in funding your account",
    "bankName": "Name of Bank",
    "amount": "Amount You're Wiring",
    "fundDate": "Wire Date",
    "success-title": "Expedite successfully",
    "success-message": "Thank You! Your account will be credited as soon as our bank receives the funds.<br/>Please ensure you type the unique ID in the payment details/comment section when you enter your money transfer to us, otherwise there may be a delay in updating the balance in your account."
  },
  "fallback": {
    "title": "Not available at Dashboard 2.0",
    "description": "This feature is coming soon. Please, use the Classic Dashboard to access this feature. Would you like to switch to Classic Dashboard right now?",
    "action": "Switch"
  },
  "settings": {
    "userProfile": "Profile",
    "application": "Application",
    "apiTokens": "API",
    "first-name": "First name",
    "last-name": "Last name",
    "email": "Email",
    "password": "Password",
    "phone": "Phone",
    "phone-not-set": "Not set",
    "create-at": "Joined Since",
    "status": "Account Verification",
    "pending": "Pending",
    "approved": "Approved",
    "declined": "Declined",
    "receive-report": "Receive report",
    "enabled": "Enabled",
    "disabled": "Disabled",
    "enable-report": "Enable Report",
    "disable-report": "Disable Report",
    "two-factor-authen": "2-Factor Authentication",
    "add-phone": "Add phone",
    "change-phone": "Change phone",
    "verify-phone": "Verify phone",
    "disable-two-factor": "Disable 2-Factor Authentication",
    "enter-verify-token": "Enter your verification token",
    "resend-token": "Resend Token via SMS",
    "modal-change-phone-number-success-message": "Change phone number successfully",
    "modal-verify-instruction": "Verification token has been sent via SMS. Or you can install {{- app}} and get token there instead (recommended)",
    "modal-verify-phone-number-success-message": "Verify phone number successfully",
    "modal-disable-confirm-title": "Disable 2-Factor Authentication Confirmation",
    "modal-disable-confirm-body": "Are you sure you want to disable 2-Factor Authentication?",
    "modal-disable-success-message": "Disable 2-Factor Authentication successfully",
    "id-document": "ID document",
    "proof-address": "Proof address",
    "bank-statement": "Bank statement",
    "submit-documents": "Submit new documents",
    "require-document": "We require ID and other documents before you can do a fiat deposit/withdrawal.\nPlease provide them below",
    "modal-documents-success-title": "Documents Uploaded",
    "modal-documents-success-message": "Your documents have been uploaded. Our staff will be reviewing and approving your account shortly.",
    "api-tokens-create": "Create new api tokens",
    "api-tokens-id": "ID",
    "api-tokens-secret": "Secret",
    "orders": "Orders",
    "trades": "Positions (Trades)",
    "tradingAccounts": "Trading Accounts",
    "accounts": "Accounts",
    "executions": "Executions",
    "read": "Read",
    "write": "Write",
    "copy-secret": "Copy Secret",
    "view-detail": "View detail",
    "hide-detail": "Hide detail",
    "delete-token": "Delete token",
    "modal-delete-token-title": "Token Delete Confirmation",
    "modal-delete-token-body": "All devices and apps which use this token will be unauthorized immediately.",
    "modal-delete-token-success-title": "Token Deleted",
    "modal-delete-token-success-message": "Delete token successfully",
    "confirmation": "Confirmation",
    "skipped-confirmation": "skipped confirmation",
    "skipped-confirmations": "skipped confirmations",
    "reset-all": "Reset all"
  },
  "change-password": {
    "title": "Change Password",
    "action": "Change Password",
    "old-password": "Old Password",
    "new-password": "Password",
    "new-password-confirm": "Password confirmation",
    "success-title": "Change password successfully",
    "success-message": "Your password has been successfully updated"
  },
};
