/* eslint-disable */

export default {
  "test": {
    "basic": "english",
    "interpolation": "quoine-{{name}}"
  },
  "whats-new": {
    "date": "1471345199",
    "title": "新着情報",
    "heading": "サイドメニューからご覧頂けます",
    "button": "新着情報がございます"
  },
  "trade-overview": {
    "baseOpenPrice": "平均約定レート",
    "pnl": "概算損益",
    "position": "建玉数量"
  },
  "history": {
    "all-orders": "注文履歴",
    "executions": "約定履歴",
    "live-orders": "注文照会",
    "positions": "ポジション照会"
  },
  "book": {
    "group": "グループ",
    "feed": "約定フィード"
  },
  "chart": {
    "add-sub-chart": "サブチャート追加",
    "remove-sub-chart": "サブチャート削除"
  },
  "blotter": {
    "switch-layout": "レイアウト変更"
  },
  "order": {
    "all": "全て",
    "avg-price": "平均約定レート",
    "buy": "買",
    "buys": "買",
    "cancel": "取消",
    "cancelled": "取消済",
    "close": "決済",
    "created-at": "注文日時",
    "disclose-quantity": "開示注文数量",
    "distance": "トレール幅",
    "distance-type": "トレールタイプ",
    "edit-price": "レート変更",
    "edit-quantity": "数量変更",
    "est-price": "平均約定レート（概算）",
    "fiat": "価格",
    "percentage": "パーセント",
    "fee": "取引手数料",
    "filled": "約定済",
    "filled-qty": "約定数量",
    "id": "注文番号",
    "interest": "日歩",
    "leverage": "信用倍率",
    "limit": "指値",
    "live": "ライブ",
    "margin": "証拠金",
    "market": "成行",
    "market_with_range": "レンジ",
    "mode": "モード",
    "net-out": "Net-Out",
    "new": "新規",
    "one-direction": "One Direction",
    "open-price": "注文レート",
    "price": "約定レート",
    "product": "通貨ペア",
    "quantity": "注文数量",
    "sell": "売",
    "sells": "売",
    "side": "売買",
    "slippage": "スリッページ",
    "spot": "現物",
    "status": "状態",
    "stop": "逆指値注文",
    "target": "区分",
    "two-direction": "Two Direction",
    "type": "注文種別",
    "trailing_stop": "トレール注文",
    "no-order-title": "注文がありません"
  },
  "order-modal": {
    "create-confirm": "注文確認",
    "create-finish-submitted": "注文送信完了",
    "create-finish-filled": "注文約定完了",
    "cancel-confirm": "注文取消確認",
    "cancel-finish": "注文取消完了",
    "edit-confirm": "注文変更確認",
    "edit-finish": "注文変更完了"
  },
  "position": {
    "account": "アカウント",
    "all": "全て",
    "close": "決済",
    "closed": "決済済",
    "open": "新規",
    "status": "状態",
    "close-all": "一括決済",
    "close-long": "買建玉一括決済",
    "close-short": "売建玉一括決済",
    "close-pnl": "一括決済",
    "close-price": "決済レート",
    "close-qty": "決済済み数量",
    "created-at": "約定日時",
    "edit-stopLoss": "決済逆指値設定",
    "edit-takeProfit": "決済指値設定",
    "id": "約定番号",
    "long": "買",
    "longs": "買",
    "margin": "証拠金",
    "open-pnl": "評価損益",
    "open-price": "約定レート",
    "open-qty": "数量",
    "pnl": "損益",
    "position": "建玉",
    "product": "通貨ペア",
    "quantity": "数量",
    "short": "売",
    "shorts": "売",
    "side": "売買",
    "stop-loss": "決済逆指値",
    "take-profit": "決済指値",
    "to-close-qty": "決済数量",
    "total-interest": "合計利子",
    "no-position-title": "建玉がありません"
  },
  "position-modal": {
    "close-confirm": "建玉決済確認",
    "close-finish": "建玉決済完了",
    "edit-confirm": "建玉変更確認",
    "edit-finish": "建玉変更完了"
  },
  "execution": {
    "created-at": "約定日時",
    "id": "注文番号",
    "order-id": "約定番号",
    "price": "約定レート",
    "product": "通貨ペア",
    "quantity": "数量",
    "side": "売買",
    "target": "区分",
    "takerSide": "受手売買",
    "all": "全",
    "buy": "買",
    "sell": "売"
  },
  "menu": {
    "accounts": "マイアカウント",
    "dashboard": "ダッシュボード",
    "settings": "設定",
    "language": "言語",
    "classic": "クラシック版へ戻る",
    "whats-new": "新着情報",
    "setting": "設定"
  },
  "product": {
    "high": "高値",
    "low": "安値",
    "volume": "24H出来高",
    "add": "通貨ペア追加"
  },
  "account": {
    "add": "アカウント追加",
    "balance": "残高",
    "balance-available": "有効残高",
    "balance-base": "クリプト残高",
    "balance-locked": "拘束残高",
    "balance-quote": "現金残高",
    "balance-total": "合計残高",
    "balance-total-fiat": "合計現金残高",
    "balance-total-crypto": "合計クリプト残高",
    "equity": "純資産",
    "interest-earned": "利息",
    "limit-orders": "指値注文",
    "loan-offers": "ローンオファー",
    "loaned-out": "ローン中",
    "margin-available": "有効証拠金",
    "margin-coverage": "証拠金維持率",
    "margin-used": "使用中証拠金",
    "pnl": "損益"
  },
  "common": {
    "cancel": "キャンセル",
    "confirm": "確認",
    "dismiss": "閉じる",
    "load-more": "もっと読み込む",
    "margin": "信用",
    "spot": "現物",
    "submit": "送信",
    "view": "閲覧",
    "edit": "編集",
    "delete": "削除",
    "update": "更新",
    "add": "追加",
    "choose-file": "ファイル選択",
    "change-file": "ファイル変更"
  },
  "confirmation": {
    "skip": "今後、この確認画面をスキップする（設定ページより変更可能）"
  },
  "sign-in": {
    "action": "ログイン",
    "code": "コード",
    "email": "メールアドレス",
    "need-code": "2要素認証が有効になっています。下の欄にAuthy若しくはSMSから取得した認証コードを入力してください。",
    "password": "パスワード",
    "resend-sms": "SMS経由でコードを再送",
    "title": "ログイン",
    "use-all-features": "ログインすることでQUOINE Exchangeの全機能がご利用頂けます。",
    "sign-up": "新規登録",
    "forgot-password": "パスワードをお忘れですか？"
  },
  "forgot-password": {
    "title": "パスワードをお忘れですか？",
    "heading": "パスワードの再設定",
    "email": "メールアドレス",
    "check-email": "ご登録のメールアドレスにパスワード再設定用のリンクを送信しました。ご確認ください。",
    "resent-successfully": "パスワード再設定用のメール再送に成功しました",
    "send": "パスワード再設定用メールを送信",
    "resend": "パスワード再設定用メールを再送信"
  },
  "reset-password": {
    "title": "パスワードの再設定",
    "heading": "新しいパスワードを入力",
    "password": "パスワード",
    "success-title": "パスワード再設定完了",
    "success-action": "ログインへ進む",
    "success-message": "パスワードの再設定に成功しました。"
  },
  "sign-up": {
    "action": "新規登録",
    "title": "新規登録",
    "country": "居住国",
    "nationality": "国籍",
    "first-name": "名",
    "last-name": "姓",
    "email": "メールアドレス",
    "password": "パスワード",
    "affiliate-code": "プロモコード（任意）",
    "term-condition": "利用規約に同意する",
    "success-title": "新規登録成功",
    "success-action": "ログインへ進む",
    "success-message": "ご登録頂きまして、誠にありがとうございます。あと少しで完了です。詳しい説明を記載したメールを送信いたしましたので、ご確認ください。",
    "sign-in": "ログイン",
    "error-unique-email": "既に登録済みのメールアドレスです。",
    "error-password": "パスワードは最低8文字で、かつ1文字以上の大文字、小文字、数字を含む必要があります。",
    "error-term-condition": "利用規約に同意する必要があります。"
  },
  "sign-out": {
    "action": "ログアウト",
    "title": "ログアウトしても宜しいですか？",
    "from-all-devices": "全てのデバイス、ブラウザーからログアウトしても宜しいですか？"
  },
  "error": {
    "order-direction-long-need-empty": "買建玉が存在するため売注文を発注することができません",
    "order-direction-short-need-empty": "売建玉が存在するため買注文を発注することができません",
    "order-price-bigger-than-min": "注文レートは1以上で入力してください",
    "order-price-limit-bigger-than-market-bid": "指値の売り注文の場合、現在のレートより高いレートを入力してください",
    "order-price-limit-smaller-than-market-ask": "指値の買い注文の場合、現在のレートよりも低いレートを入力してください",
    "order-price-stop-bigger-than-market-ask": "逆指値の買い注文の場合、現在のレートより高いレートを入力してください",
    "order-price-stop-smaller-than-market-bid": "逆指値売り注文の場合、現在のレートより低いレートを入力してください",
    "order-quantity-bigger-than-min": "最低発注量は0.01BTCです",
    "order-quantity-smaller-than-max": "最大発注量は100BTCです",
    "other": "インターナルエラーが発生しました",
    "position-stop-loss-smaller-than-market-bid": "決済逆指値は現在の最良買気配より低いレートを指定してください",
    "position-stop-loss-larger-than-market-ask": "決済逆指値は現在の最良売気配より高いレートを指定してください",
    "position-take-profit-larger-than-market-bid": "決済指値は現在の最良買気配より高いレートを指定してください",
    "position-take-profit-smaller-than-market-ask": "決済指値は現在の最良売気配より低いレートを指定してください",
    "token-is-invalid": "無効なトークンです",
    "your-password-is-incorrect": "パスワードが正しくありません",
    "password-update-failed": "パスワードの更新に失敗しました"
  },
  "language": {
    "en": "English",
    "ja": "日本語"
  },
  "transaction": {
    "title-all": "全取引",
    "id": "取引番号",
    "created-at": "取引日時",
    "loan_fee": "金利手数料",
    "trade_fee": "取引手数料",
    "debit": "借方",
    "credit": "貸方",
    "loan": "ローン",
    "repay": "返済",
    "loan_trade": "返済",
    "interest_transfer": "利子",
    "fund": "入金",
    "bought": "購入",
    "sold": "売却",
    "cross_ccy_trade": "クロスCCYトレード",
    "withdraw": "出金",
    "hot_wallet_settlement": "出金",
    "system_transfer": "システムトランスファー",
    "credit_new_register": "新規登録クレジット",
    "credit_referrer": "紹介謝礼クレジット",
    "direct_trade": "トレード"
  },
  "volume": {
    "title": "取引高",
    "email-report": "レポートをメールする",
    "email-report-choose-range-first": "レポート期間を「From」及び「To」から指定してください。",
    "from": "From",
    "to": "To"
  },
  "volume-modal": {
    "report-sent": "レポート送信完了",
    "report-check-email": "レポートをメールで送信しました。ご確認ください。"
  },
  "fund": {
    "title": "入金",
    "fiat-instruction": "{{- currency}}でのご入金の場合、下記の銀行口座まで送金してください。",
    "crypto-instruction": "{{- currency}}でのご入金の場合、下記のアドレスまで送信してください。",
    "not-support-funding": "現在、{{- currency}}でのご入金には対応しておりません。カスタマーサポートまでお問い合わせください。",
    "fund-another": "他通貨でのご入金の場合、トップメニューからアカウントを選択してください。"
  },
  "withdrawal": {
    "title": "出金",
    "action": "出金を依頼する",
    "fiat-instruction": "{{- currency}}でのご出金の場合、下記より銀行口座を選択し、金額を入力してください。",
    "crypto-instruction": "{{- currency}}でのご出金の場合、下記へ{{- currency}}アドレスを入力ください。",
    "withdraw-another": "他通貨でのご出金の場合、トップメニューからアカウントを選択してください。",
    "bank-account": "銀行口座",
    "token": "トークン",
    "amount": "金額",
    "request": "リクエスト",
    "pending": "出金承認中",
    "pending-title": "出金承認中",
    "no-pending-title": "承認待ち出金依頼はございません"
  },
  "bank": {
    "name": "銀行名",
    "branch": "支店名",
    "bankAddress": "住所",
    "swift": "SWIFTコード",
    "swift-check": "SWIFTチェック",
    "bank-statement": "銀行取引明細書",
    "reason": "理由",
    "accName": "口座名義",
    "accType": "口座タイプ",
    "accNumber": "口座番号",
    "status": "状態",
    "pending": "承認中",
    "edit": "編集",
    "new": "新規口座",
    "delete-comfirm-title": "確認",
    "delete-comfirm-message": "この銀行口座を削除しても宜しいですか？",
    "delete-success-message": "銀行口座の削除に成功しました。",
    "create-title": "銀行情報の新規作成",
    "create-heading": "銀行口座の新規作成",
    "create-success-message": "銀行口座の新規作成に成功しました。",
    "update-title": "銀行口座の情報変更",
    "update-heading": "銀行口座変更",
    "update-success-message": "銀行口座の変更に成功しました。"
  },
  "expedite": {
    "title": "入金エクスプレス反映手配",
    "action": "入金エクスプレス反映手配",
    "description": "迅速にお客様のアカウントへご入金を反映させるため、下の欄に必要な情報をご記入ください。尚、ご記入が無い場合、アカウントへのご入金反映に遅れが生じる場合がございます。予め、ご了承ください。",
    "bankName": "銀行名",
    "amount": "送金金額",
    "fundDate": "送金手続日",
    "success-title": "入金エクスプレス反映手配完了",
    "success-message": "ご入金が確認でき次第、迅速にお客様のアカウントへ入金を反映させて頂きます。お客様のご入金と分かる固有番号（口座番号等）をコメント欄にご記載ください。尚、固有番号のご記入が無い場合、アカウントへのご入金反映に遅れが生じる場合がございます。予め、ご了承ください。"
  },
  "fallback": {
    "title": "クラシック版へ戻る",
    "description": "現在、この機能は開発中のため最新版ダッシュボード上ではご利用頂けません。クラシック版へ切り替えてご利用ください。",
    "action": "クラシック版へ戻る"
  },
  "settings": {
    "userProfile": "プロフィール",
    "application": "アプリケーション",
    "apiTokens": "API",
    "first-name": "名",
    "last-name": "姓",
    "email": "メールアドレス",
    "password": "パスワード",
    "phone": "電話番号",
    "phone-not-set": "未設定",
    "create-at": "登録日時",
    "status": "アカウント認証",
    "pending": "承認待ち",
    "approved": "承認完了",
    "receive-report": "レポート受信",
    "enabled": "有効",
    "disabled": "無効",
    "enable-report": "レポート有効化",
    "disable-report": "レポート無効化",
    "two-factor-authen": "2要素認証",
    "add-phone": "電話番号追加",
    "change-phone": "電話番号変更",
    "verify-phone": "電話番号認証",
    "disable-two-factor": "2要素認証の無効化",
    "enter-verify-token": "認証トークンを入力する",
    "resend-token": "SMS経由で認証トークンを再送する",
    "modal-change-phone-number-success-message": "電話番号の変更に成功しました",
    "modal-verify-instruction": "SMS経由で認証トークンが送信されました。また{{- app}}をインストールすることで認証トークンを取得することも可能です。",
    "modal-verify-phone-number-success-message": "電話番号の認証に成功しました",
    "modal-disable-confirm-title": "2要素認証無効化の確認",
    "modal-disable-confirm-body": "本当に2要素認証を無効化しても宜しいですか？",
    "modal-disable-success-message": "2要素認証の無効化に成功しました",
    "id-document": "身分証明証",
    "proof-address": "住所確認書類",
    "bank-statement": "銀行明細書",
    "submit-documents": "新規書類送信",
    "require-document": "現金の入出金を開始される前に、身分証明証および他の書類のご登録が必要になります。\n下のフォームよりご提出ください。",
    "modal-documents-success-title": "書類をアップロード",
    "modal-documents-success-message": "書類がアップロードされました。弊社スタッフが確認後、問題なければ迅速に承認いたします。",
    "api-tokens-create": "新しくAPIトークンを生成する",
    "api-tokens-id": "ID",
    "api-tokens-secret": "秘密鍵",
    "orders": "注文",
    "trades": "建玉 (トレード)",
    "tradingAccounts": "取引アカウント",
    "accounts": "アカウント",
    "executions": "約定",
    "read": "閲覧",
    "write": "読書",
    "copy-secret": "秘密鍵をコピー",
    "view-detail": "詳細を見る",
    "hide-detail": "詳細を隠す",
    "delete-token": "トークン消去",
    "modal-delete-token-title": "トークン消去の確認",
    "modal-delete-token-body": "このトークンを使用中の全デバイスとアプリのアクセスを無効化する",
    "modal-delete-token-success-title": "トークン消去完了",
    "modal-delete-token-success-message": "トークン消去に成功しました",
    "confirmation": "確認",
    "skipped-confirmation": "確認をスキップ",
    "skipped-confirmations": "確認をスキップ",
    "reset-all": "全リセット"
  },
  "change-password": {
    "title": "パスワード変更",
    "action": "パスワード変更",
    "old-password": "現在のパスワード",
    "new-password": "新しいパスワード",
    "new-password-confirm": "新しいパスワード（確認用）",
    "success-title": "パスワード変更に成功しました",
    "success-message": "あなたのパスワードの変更に成功しました"
  }
};
