/* eslint-disable quote-props */
/* eslint comma-dangle: ["error", "always"] */
export default {
  'test': {
    'basic': 'japanese',
    'interpolation': 'quoine-{{name}}',
  },
  'trade-overview': {
    'baseOpenPrice': '平均約定レート',
    'pnl': '概算損益',
    'position': '建玉数量',
  },
  'history': {
    'all-orders': '注文履歴',
    'executions': '約定履歴',
    'live-orders': '注文照会',
    'positions': 'ポジション照会',
  },
  'book': {
    'group': 'グループ',
    'feed': '約定フィード',
  },
  'blotter': {
    'switch-layout': 'レイアウト変更',
  },
  'order': {
    'avg-price': '平均約定レート',
    'buy': '買',
    'buys': '買',
    'cancel': '取消',
    'cancelled': '取消済',
    'close': '決済',
    'created-at': '注文日時',
    'disclose-quantity': '開示注文数量',
    'distance': 'プライスディスタンス',
    'distance-type': 'ディスタンスタイプ',
    'edit-price': 'レート変更',
    'edit-quantity': '数量変更',
    'est-price': '平均約定レート（概算）',
    'fiat': '現金',
    'percentage': 'パーセント',
    'fee': '取引手数料',
    'filled': '約定済',
    'filled-qty': '約定数量',
    'id': '注文番号',
    'interest': '日歩',
    'leverage': '信用倍率',
    'limit': '指値',
    'live': 'ライブ',
    'margin': '証拠金',
    'market': '成行',
    'market_with_range': 'レンジ',
    'mode': 'モード',
    'net-out': 'Net-Out',
    'new': '新規',
    'one-direction': 'One Direction',
    'open-price': '注文レート',
    'price': '約定レート',
    'product': '通貨ペア',
    'quantity': '注文数量',
    'sell': '売',
    'sells': '売',
    'side': '売買',
    'slippage': 'スリッページ',
    'spot': '現物',
    'status': '状態',
    'stop': '逆指値注文',
    'target': '区分',
    'two-direction': 'Two Direction',
    'type': '注文種別',
    'trailing_stop': 'トレーリングストップ',
  },
  'order-modal': {
    'create-confirm': '注文確認',
    'create-finish-submitted': '注文送信完了',
    'create-finish-filled': '注文約定完了',
    'cancel-confirm': '注文取消確認',
    'cancel-finish': '注文取消完了',
    'edit-confirm': '注文変更確認',
    'edit-finish': '注文変更完了',
  },
  'position': {
    'account': 'アカウント',
    'all': '全て',
    'close': '決済',
    'close-all': '一括決済',
    'close-long': '買建玉一括決済',
    'close-short': '売建玉一括決済',
    'close-pnl': '一括決済',
    'close-price': '決済レート',
    'close-qty': '決済済み数量',
    'created-at': '約定日時',
    'edit-stopLoss': '決済逆指値変更',
    'edit-takeProfit': '決済指値変更',
    'id': '約定番号',
    'long': '買',
    'longs': '買',
    'margin': '証拠金',
    'open-pnl': '評価損益',
    'open-price': '約定レート',
    'open-qty': '数量',
    'pnl': '損益',
    'position': '建玉',
    'product': '通貨ペア',
    'quantity': '数量',
    'short': '売',
    'shorts': '売',
    'side': '売買',
    'stop-loss': '決済逆指値',
    'take-profit': '決済指値',
    'to-close-qty': '決済数量',
    'total-interest': '合計利子',
  },
  'position-modal': {
    'close-confirm': '建玉決済確認',
    'close-finish': '建玉決済完了',
    'edit-confirm': '建玉変更確認',
    'edit-finish': '建玉変更完了',
  },
  'execution': {
    'created-at': '約定日時',
    'id': '注文番号',
    'order-id': '約定番号',
    'price': '約定レート',
    'product': '通貨ペア',
    'quantity': '数量',
    'side': '売買',
    'target': '区分',
  },
  'menu': {
    'accounts': 'マイアカウント',
    'dashboard': 'ダッシュボード',
    'setting': '設定',
    'language': '言語',
    'classic': 'クラシック版へ戻る',
  },
  'product': {
    'high': '高値',
    'low': '安値',
    'volume': '24H取扱高',
    'add': '通貨ペアの追加',
  },
  'account': {
    'add': 'アカウントの追加',
    'balance': '残高',
    'balance-available': '有効残高',
    'balance-base': '仮想通貨残高',
    'balance-locked': '差押残高',
    'balance-quote': '現金残高',
    'balance-total': '合計残高',
    'balance-total-fiat': '合計現金残高',
    'balance-total-crypto': '合計仮想通貨残高',
    'equity': '純資産',
    'interest-earned': '利息',
    'limit-orders': '指値注文',
    'loan-offers': 'ローンオファー',
    'loaned-out': 'ローン中',
    'margin-available': '有効証拠金',
    'margin-coverage': '証拠金維持率',
    'margin-used': '使用中証拠金',
    'pnl': '損益',
  },
  'common': {
    'cancel': 'キャンセル',
    'confirm': '確認',
    'dismiss': '破棄',
    'load-more': 'もっと読み込む',
    'margin': '信用',
    'spot': '現物',
    'submit': '送信',
    'view': '閲覧',
    'edit': '編集',
    'delete': '削除',
    'update': '更新',
  },
  'confirmation': {
    'skip': '今後、この確認画面をスキップする（設定ページより変更可能）',
  },
  'sign-in': {
    'action': 'ログイン',
    'code': 'コード',
    'email': 'メールアドレス',
    'need-code': '2要素認証が有効になっています。下の欄にAuthy若しくはSMSから取得した認証コードを入力してください。',
    'password': 'パスワード',
    'resend-sms': 'SMS経由でコードを再送',
    'title': 'ログイン',
    'use-all-features': 'ログインすることでQUOINE Exchangeの全機能がご利用頂けます。',
    'sign-up': '新規登録',
    'forgot-password': 'パスワードをお忘れですか？',
  },
  'forgot-password': {
    'title': 'パスワードをお忘れですか？',
    'heading': 'パスワードの再設定',
    'email': 'メールアドレス',
    'check-email': 'ご登録のメールアドレスにパスワード再設定用のリンクを送信しました。ご確認ください。',
    'resent-successfully': 'パスワード再設定用のメール再送に成功しました',
    'send': 'パスワード再設定用メールを送信',
    'resend': 'パスワード再設定用メールを再送信',
  },
  'reset-password': {
    'title': 'パスワードの再設定',
    'heading': '新しいパスワードを入力',
    'password': 'パスワード',
    'success-title': 'パスワード再設定完了',
    'success-action': 'ログインへ進む',
    'success-message': 'パスワードの再設定に成功しました。',
  },
  'sign-up': {
    'action': '新規登録',
    'title': '新規登録',
    'country': '居住国',
    'nationality': '国籍',
    'first-name': '名',
    'last-name': '姓',
    'email': 'メールアドレス',
    'password': 'パスワード',
    'affiliate-code': 'プロモコード（任意）',
    'term-condition': '利用規約に同意する',
    'success-title': '新規登録成功',
    'success-action': 'ログインへ進む',
    'success-message': 'ご登録頂きまして、誠にありがとうございます。あと少しで完了です。詳しい説明を記載したメールを送信いたしましたので、ご確認ください。',
    'sign-in': 'ログイン',
    'error-unique-email': '既に登録済みのメールアドレスです。',
    'error-password': 'パスワードは最低8文字で、かつ1文字以上の大文字、小文字、数字を含む必要があります。',
    'error-term-condition': '利用規約に同意する必要があります。',
  },
  'sign-out': {
    'action': 'ログアウト',
    'title': 'ログアウトしても宜しいですか？',
    'from-all-devices': '全てのデバイス、ブラウザーからログアウトしても宜しいですか？',
  },
  'error': {
    'order-direction-long-need-empty': '買建玉が存在するため売注文を発注することができません',
    'order-direction-short-need-empty': '売建玉が存在するため買注文を発注することができません',
    'order-price-bigger-than-min': '注文レートは1以上で入力してください',
    'order-price-limit-bigger-than-market-bid': '指値の売り注文の場合、現在のレートより高いレートを入力してください',
    'order-price-limit-smaller-than-market-ask': '指値の買い注文の場合、現在のレートよりも低いレートを入力してください',
    'order-price-stop-bigger-than-market-ask': '逆指値の買い注文の場合、現在のレートより高いレートを入力してください',
    'order-price-stop-smaller-than-market-bid': '逆指値売り注文の場合、現在のレートより低いレートを入力してください',
    'order-quantity-bigger-than-min': '最低発注量は0.01BTCです',
    'order-quantity-smaller-than-max': '最大発注量は100BTCです',
    'other': 'インターナルエラーが発生しました',
  },
  'language': {
    'en': 'English',
    'ja': '日本語',
  },
  'transaction': {
    'title-all': '全ての取引',
    'id': '取引番号',
    'created-at': '取引日時',
    // type
    'loan_fee': '金利手数料',
    'trade_fee': '取引手数料',
    'debit': '借方',
    'credit': '貸方',
    'loan': 'ローン',
    'repay': '返済',
    'loan_trade': '返済',
    'interest_transfer': '利子',
    'fund': '入金',
    'bought': '購入',
    'sold': '売却',
    'cross_ccy_trade': 'クロスCCYトレード',
    'withdraw': '出金',
    'hot_wallet_settlement': '出金',
    'system_transfer': 'システムトランスファー',
    'credit_new_register': '新規登録クレジット',
    'credit_referrer': '紹介謝礼クレジット',
    'direct_trade': 'トレード',
  },
  'volume': {
    'title': '取引高',
    'email-report': 'レポートをメールする',
    'email-report-choose-range-first': 'レポート期間を「From」及び「To」から指定してください。',
    'from': 'From',
    'to': 'To',
  },
  'volume-modal': {
    'report-sent': 'レポート送信完了',
    'report-check-email': 'レポートをメールで送信しました。ご確認ください。',
  },
  'fund': {
    'title': '入金',
    'fiat-instruction': '{{- currency}}でのご入金の場合、下記の銀行口座まで送金してください。',
    'crypto-instruction': '{{- currency}}でのご入金の場合、下記のアドレスまで送信してください。',
    'fund-another': '他通貨でのご入金の場合、トップメニューからアカウントを選択してください。',
  },
  'withdrawal': {
    'title': '出金',
    'action': '出金を依頼する',
    'fiat-instruction': '{{- currency}}でのご出金の場合、下記より銀行口座を選択し、金額を入力してください。',
    'crypto-instruction': '{{- currency}}でのご出金の場合、下記へ{{- currency}}アドレスを入力ください。',
    'withdraw-another': '他通貨でのご出金の場合、トップメニューからアカウントを選択してください。',
    'bank-account': '銀行口座',
    'token': 'トークン',
    'amount': '金額',
    'request': 'リクエスト',
  },
  'bank': {
    'name': '銀行名',
    'branch': '支店名',
    'bankAddress': '住所',
    'swift': 'SWIFTコード',
    'swift-check': 'SWIFTチェック',
    'bank-statement': '銀行取引明細書',
    'reason': '理由',
    'accName': '口座名義',
    'accType': '口座タイプ',
    'accNumber': '口座番号',
    'status': '状態',
    'pending': '承認中',
    'edit': '編集',
    'new': '新規口座',
    'delete-comfirm-title': '確認',
    'delete-comfirm-message': 'この銀行口座を削除しても宜しいですか？',
    'delete-success-message': '銀行口座の削除に成功しました。',
    'create-title': '銀行情報の新規作成',
    'create-heading': '銀行口座の新規作成',
    'create-success-message': '銀行口座の新規作成に成功しました。',
    'update-title': '銀行口座の情報変更',
    'update-heading': '銀行口座変更',
    'update-success-message': '銀行口座の変更に成功しました。',
  },
  'expedite': {
    'title': '入金エクスプレス反映手配',
    'action': '入金エクスプレス反映手配',
    'description': '迅速にお客様のアカウントへご入金を反映させるため、下の欄に必要な情報をご記入ください。尚、ご記入が無い場合、アカウントへのご入金反映に遅れが生じる場合がございます。予め、ご了承ください。',
    'bankName': '銀行名',
    'amount': '送金金額',
    'fundDate': '送金手続日',
    'success-title': '入金エクスプレス反映手配完了',
    'success-message': 'ご入金が確認でき次第、迅速にお客様のアカウントへ入金を反映させて頂きます。お客様のご入金と分かる固有番号（口座番号等）をコメント欄にご記載ください。尚、固有番号のご記入が無い場合、アカウントへのご入金反映に遅れが生じる場合がございます。予め、ご了承ください。',
  },
  'fallback': {
    'title': 'クラシック版へ戻る',
    'description': '現在、この機能は開発中のため最新版ダッシュボード上ではご利用頂けません。クラシック版へ切り替えてご利用ください。',
    'action': 'クラシック版へ戻る',
  },
};
