/* eslint-disable quote-props */
/* eslint comma-dangle: ["error", "always"] */
export default {
  'test': {
    'basic': 'japanese',
    'interpolation': 'quoine-{{name}}',
  },
  'order': {
    'limit': '指値注文',
    'market': '成行注文',
    'stop': '逆指値注文',
    'quantity': '注文数量',
    'disclose-quantity': '開示注文数量',
    'price': '注文価格',
    'mode': 'Mode',
    'one-direction': 'One Direction',
    'two-direction': 'Two Direction',
    'net-out': 'Net-Out',
    'slippage': 'Slippage',
    'leverage': 'Leverage',
    'fee': '手数料',
    'cost': '概算',
    'margin': '信用倍率',
    'interest': '金利（日歩）',
  },
  'menu': {
    'dashboard': 'ビットコイン売買',
    'accounts': 'マイページ',
    'setting': '信用設定',
  },
  'product': {
    'low': '安値',
    'high': '高値',
    'volume': '24時間取扱高',
  },
  'account': {
    'pnl': '損益',
    'balance': '現金残高',
    'balance-total': '総資産',
    'balance-quote': '資産',
    'balance-base': '仮想通貨資産',
    'equity': '評価残高',
    'margin-used': '使用中証拠金額',
    'margin-available': '信用取引余力',
    'margin-coverage': '証拠金維持率',
  },
  'common': {
    'spot': '現物取引',
    'margin': '信用取引',
    'buy': '買',
    'sell': '売',
  },
  'sign-in': {
    'title': 'サインイン',
    'use-all-features': 'Sign in to use all features of QUOINE Exchange',
    'email': 'Eメール',
    'password': 'パスワード',
    'action': 'サインイン',
  },
};
